#!/bin/bash

[[ $# == 0 ]] && cat <<EOHELP && exit 1
Usage: tmax <host1 [hostN...]>
EOHELP

if [ "$1" == "-l" ]; then
	USER=$2
	shift; shift
fi

# Stuff arguments in an array
Hosts=($@)

# Create new tmux session
session=$(date +%h%d_%I%M%S)
echo Connecting as $USER...
tmux new-session -s $session -d "echo Connecting to ${Hosts[0]}...; ssh ${USER}@${Hosts[0]}; echo -e \n[Finished]; read x"
echo session: $session

# Set limit on number of panes to create
pmax=$#; count=1
while [ $count -lt $pmax ]; do
	# Get next set of panes to split
	pset=$(tmux list-pane -t $session:0 | awk -F: '{print $1}')
	for s in $pset; do

		# countreate the new pane
		tmux split-window -t $session:0.$s -h "echo Connecting to ${Hosts[$count]}...; ssh ${USER}@${Hosts[$count]}; echo -e \n[Finished]; read x"
		((count++))
		if [ $count -eq $pmax ]; then
			break
		fi
	done
done

# All done, organize and set options
tmux select-layout -t $session:0 tiled
tmux select-pane -t $session:0.0
tmux set-window-option -t $session:0 synchronize-panes on
#tmux attach-session -t $session
